# Generated by Django 4.2.4 on 2023-08-12 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_birdseed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='birdseed',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='birdseed',
            name='date',
            field=models.DateField(verbose_name='feeding date'),
        ),
    ]
